# Generated by Django 5.2.4 on 2025-09-11 00:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('matricula_funcionario', models.PositiveIntegerField(max_length=6, primary_key=True, serialize=False)),
                ('nome_funcionario', models.CharField(max_length=60, validators=[django.core.validators.RegexValidator('^[a-zA-ZáàâãéèêióôõúçñÁÀÂÃÉÈÊIÓÔÕÚÇÑ\\s]+$', 'Apenas letras são permitido no nome.')], verbose_name='Nome Funcionario')),
                ('status', models.CharField(choices=[('SIM', 'Banheirista'), ('NAO', 'Não Banheirista')], default='NAO', max_length=3, verbose_name='Status')),
                ('ferias', models.CharField(blank=True, choices=[('JAN', 'Janeiro'), ('FEV', 'Fevereiro'), ('MAR', 'Março'), ('ABR', 'ABRIL'), ('MAI', 'MAIO'), ('JUN', 'Junho'), ('JUL', 'Julho'), ('AGO', 'Agosto'), ('SET', 'Setembro'), ('OUT', 'Outubro'), ('NOV', 'Novembro'), ('DEZ', 'Desembro')], max_length=3, null=True, verbose_name='Ferias')),
            ],
        ),
        migrations.CreateModel(
            name='Setores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(max_length=40, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9áàâãéèêióôõúçñÁÀÂÃÉÈÊIÓÔÕÚÇÑ\\s]+$', 'Apenas letras são permitido no nome.')], verbose_name='Setores')),
                ('funcionario_setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setores', to='colaboradores.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Uniformes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calca', models.CharField(choices=[('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG'), ('EXTRAG', 'EXTRA GG')], max_length=6, verbose_name='Calça')),
                ('blusa', models.CharField(choices=[('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG'), ('EXTRAG', 'EXTRA GG')], max_length=6, verbose_name='Blusa')),
                ('blusa_frio', models.CharField(choices=[('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG'), ('EXTRAG', 'EXTRA GG')], max_length=6, verbose_name='Blusa de Frio')),
                ('sapato', models.PositiveSmallIntegerField(choices=[(34, '34'), (35, '35'), (36, '36'), (37, '37'), (38, '38'), (39, '39'), (40, '40'), (41, '41'), (42, '42'), (43, '43'), (44, '44'), (45, '45')], validators=[django.core.validators.MinValueValidator(34), django.core.validators.MaxValueValidator(45)], verbose_name='Sapato')),
                ('galocha', models.PositiveSmallIntegerField(choices=[(34, '34'), (35, '35'), (36, '36'), (37, '37'), (38, '38'), (39, '39'), (40, '40'), (41, '41'), (42, '42'), (43, '43'), (44, '44'), (45, '45')], validators=[django.core.validators.MinValueValidator(34), django.core.validators.MaxValueValidator(45)])),
                ('funcionario_uniforme', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uniformes', to='colaboradores.funcionario')),
            ],
        ),
    ]
