# Generated by Django 6.0.5 on 2026-05-24 19:22

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('preposta', 'Preposta'), ('encarregada', 'Encarregada')], default='encarregada', max_length=15, verbose_name='Perfil')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9áàâãéèêióôõúçñÁÀÂÃÉÈÊIÓÔÕÚÇÑ\\s]+$', 'Apenas letras são permitidas no nome.')], verbose_name='Nome')),
                ('encarregada', models.ForeignKey(blank=True, limit_choices_to={'role': 'encarregada'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setores', to=settings.AUTH_USER_MODEL, verbose_name='Encarregada responsável')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('matricula_funcionario', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nome_funcionario', models.CharField(max_length=60, validators=[django.core.validators.RegexValidator('^[a-zA-ZáàâãéèêióôõúçñÁÀÂÃÉÈÊIÓÔÕÚÇÑ\\s]+$', 'Apenas letras são permitidas no nome.')], verbose_name='Nome Funcionário')),
                ('status', models.CharField(choices=[('SIM', 'Banheirista'), ('NAO', 'Não Banheirista')], default='NAO', max_length=3, verbose_name='Status')),
                ('ferias', models.CharField(blank=True, choices=[('JAN', 'Janeiro'), ('FEV', 'Fevereiro'), ('MAR', 'Março'), ('ABR', 'ABRIL'), ('MAI', 'MAIO'), ('JUN', 'Junho'), ('JUL', 'Julho'), ('AGO', 'Agosto'), ('SET', 'Setembro'), ('OUT', 'Outubro'), ('NOV', 'Novembro'), ('DEZ', 'Desembro')], max_length=3, null=True, verbose_name='Férias')),
                ('encarregada', models.ForeignKey(blank=True, limit_choices_to={'role': 'encarregada'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionarios', to=settings.AUTH_USER_MODEL, verbose_name='Encarregada responsável')),
                ('setores', models.ManyToManyField(blank=True, related_name='funcionarios', to='colaboradores.setor')),
            ],
        ),
        migrations.CreateModel(
            name='Uniforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calca', models.CharField(choices=[('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG'), ('EXTRAG', 'EXTRA GG')], max_length=6, verbose_name='Calça')),
                ('blusa', models.CharField(choices=[('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG'), ('EXTRAG', 'EXTRA GG')], max_length=6, verbose_name='Blusa')),
                ('blusa_frio', models.CharField(choices=[('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG'), ('EXTRAG', 'EXTRA GG')], max_length=6, verbose_name='Blusa de Frio')),
                ('sapato', models.PositiveSmallIntegerField(choices=[(34, '34'), (35, '35'), (36, '36'), (37, '37'), (38, '38'), (39, '39'), (40, '40'), (41, '41'), (42, '42'), (43, '43'), (44, '44'), (45, '45')], validators=[django.core.validators.MinValueValidator(34), django.core.validators.MaxValueValidator(45)], verbose_name='Sapato')),
                ('galocha', models.PositiveSmallIntegerField(choices=[(34, '34'), (35, '35'), (36, '36'), (37, '37'), (38, '38'), (39, '39'), (40, '40'), (41, '41'), (42, '42'), (43, '43'), (44, '44'), (45, '45')], validators=[django.core.validators.MinValueValidator(34), django.core.validators.MaxValueValidator(45)])),
                ('funcionario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uniforme', to='colaboradores.funcionario')),
            ],
        ),
    ]
