# Generated by Django 5.0.4 on 2025-10-09 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='uniforme',
        ),
        migrations.AddField(
            model_name='uniformes',
            name='uniforme',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uniformes', to='colaboradores.funcionario'),
        ),
    ]
