# Generated by Django 5.2.4 on 2025-09-06 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uniformes',
            name='matricula_funcionario',
        ),
        migrations.AddField(
            model_name='uniformes',
            name='matricula_funcionario_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uniformes', to='colaboradores.funcionario'),
        ),
    ]
