# Generated by Django 5.0.4 on 2025-10-09 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0002_remove_funcionario_uniforme_uniformes_uniforme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uniformes',
            old_name='uniforme',
            new_name='funcionario',
        ),
    ]
