# Generated by Django 5.2.4 on 2025-09-02 23:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0002_alter_funcionario_ferias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='matricula_funcionario',
            field=models.PositiveIntegerField(max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='setores',
            name='matricula_funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setores', to='colaboradores.funcionario'),
        ),
        migrations.AlterField(
            model_name='setores',
            name='setor',
            field=models.CharField(max_length=40, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9áàâãéèêióôõúçñÁÀÂÃÉÈÊIÓÔÕÚÇÑ\\s]+$', 'Apenas letras são permitido no nome.')], verbose_name='Setores'),
        ),
    ]
