# Generated by Django 5.2.4 on 2025-09-03 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0003_alter_funcionario_matricula_funcionario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='ferias',
            field=models.CharField(blank=True, choices=[('JAN', 'Janeiro'), ('FEV', 'Fevereiro'), ('MAR', 'Marcio'), ('ABR', 'ABRIL'), ('MAI', 'MAIO'), ('JUN', 'Junho'), ('JUl', 'Julho'), ('AGO', 'Agosto'), ('SET', 'Setembro'), ('OUT', 'Outubro'), ('NOV', 'Novembro'), ('DES', 'Desembro')], max_length=3, null=True, verbose_name='Ferias'),
        ),
    ]
