# Generated by Django 5.2.4 on 2025-10-15 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0003_rename_uniforme_uniformes_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniformes',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uniformes', to='colaboradores.funcionario'),
        ),
    ]
