# Generated by Django 5.0.4 on 2025-10-16 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0004_alter_uniformes_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniformes',
            name='funcionario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uniformes', to='colaboradores.funcionario'),
        ),
    ]
