# Generated by Django 5.2.4 on 2025-09-04 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0004_alter_funcionario_ferias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniformes',
            name='matricula_funcionario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uniformes', to='colaboradores.funcionario'),
        ),
    ]
